import 'dart:convert';
import 'package:flutter/services.dart';
import '../models/ocr_result.dart';

/// Fast medicine matcher using a pre-built inverted word index.
///
/// Asset layout:
///   assets/data/medicines_index.json   ← generated by build script
///
/// JSON structure:
///   {
///     "names": ["ABILIFY", "ABACT", ...],          // 3 813 unique names
///     "index": { "ABILIFY": [0], "ABACT": [1], ... } // word → [nameIdx]
///   }
class MedicineMatcherService {
  List<String> _names = [];
  Map<String, List<int>> _index = {};
  bool get isReady => _names.isNotEmpty;

  // ── Load ──────────────────────────────────────────────────────────────────

  Future<void> load() async {
    final raw = await rootBundle.loadString('assets/data/medicines_index.json');
    final Map<String, dynamic> json = jsonDecode(raw);

    _names = List<String>.from(json['names'] as List);

    final rawIndex = json['index'] as Map<String, dynamic>;
    _index = rawIndex.map(
      (k, v) => MapEntry(k, List<int>.from(v as List)),
    );
  }

  // ── Public entry point ────────────────────────────────────────────────────

  /// Parse [ocrText] and return a structured [OcrResult].
  OcrResult parse(String ocrText) {
    final String cleaned = _normalize(ocrText);
    final List<String> words = _tokenize(cleaned);

    final String? matchedName = _matchName(words, cleaned);
    final String? dosage = _extractDosage(cleaned);
    final String? form = _extractForm(cleaned);

    return OcrResult(
      matchedName: matchedName,
      form: form,
      dosage: dosage,
      rawText: ocrText,
      confidence: matchedName != null ? 0.85 : 0.0,
    );
  }

  // ── Name matching via inverted index ─────────────────────────────────────

  String? _matchName(List<String> words, String cleaned) {
    // Step 1: collect candidate name indices via the inverted index
    final Map<int, int> hitCount = {}; // nameIdx → how many of its words matched
    for (final w in words) {
      if (w.length < 3) continue;
      final hits = _index[w];
      if (hits != null) {
        for (final idx in hits) {
          hitCount[idx] = (hitCount[idx] ?? 0) + 1;
        }
      }
      // Also try OCR error corrections on this word
      for (final corrected in _ocrVariants(w)) {
        final hitsC = _index[corrected];
        if (hitsC != null) {
          for (final idx in hitsC) {
            hitCount[idx] = (hitCount[idx] ?? 0) + 1;
          }
        }
      }
    }

    if (hitCount.isEmpty) return null;

    // Step 2: rank candidates by hit count, then by Levenshtein similarity
    const double threshold = 0.72;
    String? bestName;
    double bestScore = 0.0;

    // Only evaluate top-20 candidates (index already filtered the rest)
    final topCandidates = hitCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final evalSet = topCandidates.take(20);

    for (final entry in evalSet) {
      final String name = _names[entry.key];
      // Fast exact-contain check first
      if (cleaned.contains(name)) return name;

      final double score = _nameScore(name, words);
      if (score > bestScore) {
        bestScore = score;
        bestName = name;
      }
    }

    return bestScore >= threshold ? bestName : null;
  }

  /// Compute a match score for [name] against the OCR [words].
  double _nameScore(String name, List<String> words) {
    final List<String> nameWords = _tokenize(name);
    final significantWords = nameWords.where((w) => w.length >= 3).toList();
    if (significantWords.isEmpty) return 0.0;

    int matched = 0;
    double totalSim = 0.0;

    for (final nw in significantWords) {
      double best = 0.0;
      for (final ow in words) {
        if (ow.length < 3) continue;
        final s = _levenshteinSimilarity(nw, ow);
        if (s > best) best = s;
      }
      if (best >= 0.75) {
        matched++;
        totalSim += best;
      }
    }

    if (matched == 0) return 0.0;
    final coverage = matched / significantWords.length;
    return (totalSim / significantWords.length) * coverage;
  }

  // ── Dosage extraction ─────────────────────────────────────────────────────

  // Common dosage units in the Moroccan pharmacopoeia
  static const List<String> _dosageUnits = [
    'MBQ', 'GBQ', 'NMOL', 'MMOL', 'MUI', 'MCG',
    'MG/ML', 'MG/G', 'G/ML', 'UI/ML',
    'MG', 'ML', 'UI', 'IE', 'UG', 'G', '%',
  ];

  /// Returns the first dosage token found in [text], e.g. "500 MG" or "1 G/5 ML".
  /// Returns null if nothing matches.
  String? _extractDosage(String text) {
    // Pattern: number(s) followed by a unit, optionally combined "/ number unit"
    // e.g. "500 MG", "1,5 G", "125 MG/5 ML", "0,5 %"
    final unitPattern = _dosageUnits.map(RegExp.escape).join('|');
    final re = RegExp(
      r'(\d[\d,\.]*\s*(?:' + unitPattern + r')(?:\s*/\s*\d[\d,\.]*\s*(?:' + unitPattern + r'))*)',
      caseSensitive: false,
    );
    final match = re.firstMatch(text);
    if (match == null) return null;
    return match.group(0)!.trim().toUpperCase();
  }

  // ── Form extraction ───────────────────────────────────────────────────────

  /// Canonical form keywords, ordered from most-specific to least-specific.
  /// Each entry: (French keyword, display label FR, display label EN)
  static const List<_FormEntry> _forms = [
    // Injectables & perfusions
    _FormEntry('INJECTABLE', 'Injectable', 'Injectable'),
    _FormEntry('PERFUSION', 'Perfusion', 'Infusion'),
    _FormEntry('SERINGUE', 'Seringue pré-remplie', 'Pre-filled syringe'),
    _FormEntry('LYOPHILISAT', 'Lyophilisat', 'Lyophilisate'),
    // Oral solids
    _FormEntry('COMPRIME EFFERVESCENT', 'Comprimé effervescent', 'Effervescent tablet'),
    _FormEntry('COMPRIME DISPERSIBLE', 'Comprimé dispersible', 'Dispersible tablet'),
    _FormEntry('COMPRIME ORODISPERSIBLE', 'Comprimé orodispersible', 'Orodispersible tablet'),
    _FormEntry('COMPRIME SUBLINGUAL', 'Comprimé sublingual', 'Sublingual tablet'),
    _FormEntry('COMPRIME A CROQUER', 'Comprimé à croquer', 'Chewable tablet'),
    _FormEntry('COMPRIME A LIBERATION', 'Comprimé LP', 'Modified-release tablet'),
    _FormEntry('COMPRIME GASTRO', 'Comprimé gastro-résistant', 'Gastro-resistant tablet'),
    _FormEntry('COMPRIMES PELLICULES', 'Comprimé pelliculé', 'Film-coated tablet'),
    _FormEntry('COMPRIME PELLICULE', 'Comprimé pelliculé', 'Film-coated tablet'),
    _FormEntry('COMPRIME SECABLE', 'Comprimé sécable', 'Scored tablet'),
    _FormEntry('COMPRIME ENROBE', 'Comprimé enrobé', 'Coated tablet'),
    _FormEntry('COMPRIME', 'Comprimé', 'Tablet'),
    // Capsules & gélules
    _FormEntry('GELULE A LIBERATION', 'Gélule LP', 'Modified-release capsule'),
    _FormEntry('GELULE GASTRO', 'Gélule gastro-résistante', 'Gastro-resistant capsule'),
    _FormEntry('GELULE', 'Gélule', 'Capsule'),
    _FormEntry('CAPSULE MOLLE', 'Capsule molle', 'Soft capsule'),
    _FormEntry('CAPSULE', 'Capsule', 'Capsule'),
    // Liquids oral
    _FormEntry('SIROP', 'Sirop', 'Syrup'),
    _FormEntry('SUSPENSION BUVABLE', 'Suspension buvable', 'Oral suspension'),
    _FormEntry('SOLUTION BUVABLE', 'Solution buvable', 'Oral solution'),
    _FormEntry('POUDRE POUR SUSPENSION BUVABLE', 'Poudre susp. buvable', 'Powder oral suspension'),
    _FormEntry('SACHET', 'Sachet', 'Sachet'),
    _FormEntry('GRANULE', 'Granulé', 'Granules'),
    // Topicals
    _FormEntry('CREME', 'Crème', 'Cream'),
    _FormEntry('POMMADE', 'Pommade', 'Ointment'),
    _FormEntry('GEL', 'Gel', 'Gel'),
    _FormEntry('LOTION', 'Lotion', 'Lotion'),
    _FormEntry('PATCH', 'Patch transdermique', 'Transdermal patch'),
    // Respiratory
    _FormEntry('AEROSOL', 'Aérosol', 'Aerosol / Inhaler'),
    _FormEntry('INHALATION', 'Inhalation', 'Inhalation'),
    // Eyes / Ears / Nose
    _FormEntry('COLLYRE', 'Collyre', 'Eye drops'),
    _FormEntry('AEROSOL NASAL', 'Spray nasal', 'Nasal spray'),
    _FormEntry('COLLUTOIRE', 'Collutoire', 'Mouth spray'),
    // Rectal / Vaginal
    _FormEntry('SUPPOSITOIRE', 'Suppositoire', 'Suppository'),
    _FormEntry('OVULE', 'Ovule vaginal', 'Vaginal ovule'),
    // Other
    _FormEntry('BAIN DE BOUCHE', 'Bain de bouche', 'Mouthwash'),
    _FormEntry('BAUME', 'Baume', 'Balm'),
  ];

  String? _extractForm(String text) {
    for (final entry in _forms) {
      if (text.contains(entry.keyword)) return entry.displayFr;
    }
    return null;
  }

  // ── Text normalisation ────────────────────────────────────────────────────

  String _normalize(String text) {
    return text
        .toUpperCase()
        // Common OCR digit→letter confusions on medicine boxes
        .replaceAll('0', 'O')
        .replaceAll('1', 'I')
        .replaceAll('5', 'S')
        // Strip noise
        .replaceAll(RegExp(r'[^A-Z0-9\s/,\.%µ]'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  List<String> _tokenize(String text) =>
      text.split(RegExp(r'[\s/\-,\.]+')).where((w) => w.length >= 2).toList();

  // Common single-character OCR substitutions to try as variants
  List<String> _ocrVariants(String word) {
    // Reverse the normalize substitutions to find original word
    final variants = <String>[];
    // O→0, I→1, S→5 reversals in the name
    if (word.contains('O')) variants.add(word.replaceAll('O', '0'));
    if (word.contains('I')) variants.add(word.replaceAll('I', '1'));
    if (word.contains('S')) variants.add(word.replaceAll('S', '5'));
    return variants;
  }

  // ── Levenshtein similarity ────────────────────────────────────────────────

  double _levenshteinSimilarity(String a, String b) {
    if (a == b) return 1.0;
    if (a.isEmpty || b.isEmpty) return 0.0;
    final int la = a.length, lb = b.length;
    // Quick length filter — skip if too different
    if ((la - lb).abs() > (la > lb ? la : lb) * 0.4) return 0.0;

    List<int> prev = List.generate(lb + 1, (j) => j);
    List<int> curr = List.filled(lb + 1, 0);

    for (int i = 1; i <= la; i++) {
      curr[0] = i;
      for (int j = 1; j <= lb; j++) {
        if (a[i - 1] == b[j - 1]) {
          curr[j] = prev[j - 1];
        } else {
          curr[j] = 1 +
              [prev[j], curr[j - 1], prev[j - 1]]
                  .reduce((x, y) => x < y ? x : y);
        }
      }
      final tmp = prev;
      prev = curr;
      curr = tmp;
    }
    final dist = prev[lb];
    final maxLen = la > lb ? la : lb;
    return 1.0 - dist / maxLen;
  }
}

// ── Helper ────────────────────────────────────────────────────────────────────

class _FormEntry {
  final String keyword;
  final String displayFr;
  final String displayEn;
  const _FormEntry(this.keyword, this.displayFr, this.displayEn);
}